### ISSUE TITLE
MatlabAPI does not work

### ISSUE THREAD

**Issue by manyaafonso** [cocodataset/cocoapi#190]
When I try to build in Matlab R2017 (Linux Mint 18.1), I get:
mex maskApiMex.c
Building with 'gcc'.
Error using mex
/home/mafonso/cocoapi/MatlabAPI/private/maskApiMex.c:8:21: fatal error: maskApi.h: No such file or directory
 #include "maskApi.h"
                     ^
compilation terminated.

At least provide the complete source code if you are deleting the precompiled binaries.

**Comment by yaoqi-zd** [comment]
@manyaafonso Hi, I'm facing the same problem. have you fixed it ?

**Comment by manyaafonso** [comment]
@yaoqi-zd I have not fixed it but found the binaries from a forked version: https://github.com/nightrome/cocostuffapi/tree/master/MatlabAPI/private

**Comment by yaoqi-zd** [comment]
@manyaafonso thanks!
